name: CI
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest black ruff
      - name: Lint (ruff)
        run: ruff check .
      - name: Style (black --check)
        run: black --check .
      - name: Tests
        run: pytest -q
